name: Build Portabler

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build solution
      run: msbuild Portabler.sln /p:Configuration=Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: portabler-build
        path: |
          **\bin\Release\**
